export const productsList = [
  {
    id: '1',
    cssClass: 'model3',
    name: 'Model 3',
    description: 'Order Online for Touchless Delivery',
    firstBtnLabel: 'CUSTOM ORDER',
    firstBtnURL: 'https://www.tesla.com/model3/design',
    secondBtnLabel: 'EXISTING INVENTORY',
    secondBtnURL: 'https://www.tesla.com/inventory/new/m3',
  },
  {
    id: '2',
    cssClass: 'modely',
    name: 'Model Y',
    description: 'Order Online for Touchless Delivery',
    firstBtnLabel: 'CUSTOM ORDER',
    firstBtnURL: 'https://www.tesla.com/modely/design',
    secondBtnLabel: 'EXISTING INVENTORY',
    secondBtnURL: 'https://www.tesla.com/inventory/new/my',
  },
  {
    id: '3',
    cssClass: 'models',
    name: 'Model S',
    description: 'Order Online for Touchless Delivery',
    firstBtnLabel: 'CUSTOM ORDER',
    firstBtnURL: 'https://www.tesla.com/models/design',
    secondBtnLabel: 'EXISTING INVENTORY',
    secondBtnURL: 'https://www.tesla.com/inventory/new/ms',
  },
  {
    id: '4',
    cssClass: 'modelx',
    name: 'Model X',
    description: 'Order Online for Touchless Delivery',
    firstBtnLabel: 'CUSTOM ORDER',
    firstBtnURL: 'https://www.tesla.com/modelx/design',
    secondBtnLabel: 'EXISTING INVENTORY',
    secondBtnURL: 'https://www.tesla.com/inventory/new/mx',
  },
  {
    id: '5',
    cssClass: 'solarpanels',
    name: 'Solar Panels',
    description: 'Lowest Cost Solar Panels in America',
    firstBtnLabel: 'ORDER NOW',
    firstBtnURL: 'https://www.tesla.com/energy/design',
    secondBtnLabel: 'LEARN MORE',
    secondBtnURL: 'https://www.tesla.com/solarpanels',
  },
  {
    id: '6',
    cssClass: 'solarroof',
    name: 'Solar Roof',
    description: 'Produce Clean Energy From Your Roof',
    firstBtnLabel: 'ORDER NOW',
    firstBtnURL: 'https://www.tesla.com/solarroof/design',
    secondBtnLabel: 'LEARN MORE',
    secondBtnURL: 'https://www.tesla.com/solarroof',
  },
  {
    id: '7',
    cssClass: 'accessories',
    name: 'Accessories',
    firstBtnLabel: 'SHOP NOW',
    firstBtnURL: 'https://www.tesla.com/shop?tesref=true',
  },
];
